### ISSUE TITLE
Feature request: Screen Sharing

### ISSUE THREAD

**Issue by jabis** [meething/webrtc-gun#10]
Love what you're doing here!! 

I'd like to request a feature: screen sharing, something like [muaz-khan](
https://github.com/muaz-khan/WebRTC-Experiment/blob/master/Pluginfree-Screen-Sharing/conference.js) has acchieved, would be super useful feature :)

I hope I am able to contribute in your repo soon-ish, but a bit busy ATM.

You can ping me at GUN discord/gitter tho :)

BR,
Jabis

**Comment by QVDev** [comment]
Hi Jabis,

this is definitely something that possible and we will consider implementing it when we expand the features.

Thanks for the request.

**Comment by lmangani** [comment]
Thanks @jabis ! Any contribution is super welcome and being this based off standard webrtc demos, it should be quite easy to import features such as muazkhan's demos. Happy to help you whenever you want to give this a try!
