### ISSUE TITLE
GUN Chatroom

### ISSUE THREAD

**Issue by lmangani** [meething/webrtc-gun#11]
Rather than reinventing the wheel, it would be great if this app could join a distributed Gun Chat leveraging all community features/ideas or integrating with existing networks. If anyone's willing to come in help us design and implement this subsystem please stand up :)

**Comment by QVDev** [comment]
Currently the chat seems to be broken.

**Comment by Dletta** [comment]
I have some chat code but @throwness has been looking at iris.to quite a bit. might be easily integrated with it
