### ISSUE TITLE
[Idea] replace Bootstrap with plain CSS Grid and styles

### ISSUE THREAD

**Issue by thrownness** [meething/webrtc-gun#17]
https://github.com/meething/webrtc-gun/blob/master/src/index.html#L13

Replacing bootstrap with plain CSS grid and styles would make the app more lightweight. It looks like Bootstrap is mainly just used for column and row layout too.

Would need to test if this would affect "dragable" css though. Unsure of what that plugin does today in the app.

**Comment by Dletta** [comment]
I think we moved to gridster, this can be closed
