### ISSUE TITLE
Console Reveals Room Names

### ISSUE THREAD

**Issue by Dletta** [meething/webrtc-gun#23]
When other users create a new room, the DAM inbound blocker reveals the room name.

This is obviously because it's experimental. But this is a reminder to remove the room name before going production.

**Comment by lmangani** [comment]
Good point @Dletta that's indeed correct as we're in "debug" mode where we still allow certain messages on the login page from the former version. @QVDev is working on this a lot and in the next iteration, Gun should be loaded only after the room is determined and a sub-mesh is gets formed in the dedicated websocket gun.

**Comment by QVDev** [comment]
Indeed, we going to remove the presence of user in the main part. And we will use specific room gun instance based on https://github.com/meething/gundb-multisocket this will give everyone room the privacy we are aiming for

**Comment by QVDev** [comment]
This should be solved with #27
