### ISSUE TITLE
Streaming is Broken: WebSocket connection to  'https://us.meething.space:8787/demo?creator=test' failed

### ISSUE THREAD

**Issue by seanh0895** [meething/webrtc-gun#277]
When I try to join a call with room "demo" and username "test", the video stream does not work. And in the console the following error is present:

**_WebSocket connection to  'https://us.meething.space:8787/demo?creator=test' failed_** 

In src/assets/js/config.js 'https://us.meething.space:8787' is the value of the config variable **_"multigun"_**

It appears that the multigun config variable is used to create the streaming via roomPeer in the initSocket function(line 120) of src/assets/js/main.js  

It also appears that "meething.space" is no longer hosting the meething demo linked in this repo.

Is there a different url that I can swap out for 'https://us.meething.space:8787' 

What is multgun?  How do I build my own multigun? Is there a repo for multigun?

**Comment by lmangani** [comment]
Sadly the old infra keeping meething alive is slowly dissolving.... [webrtctzn](https://github.com/meething/webrtctzn) still works and should continue working indefinitely but it doesn't use gun and relies on bittorrent DHTs and pure p2p webrtc

This is the [gun multisocket service](https://github.com/meething/gundb-multisocket) meething used to create disposable gun "rooms" used to vehicle both webrtc signaling and messaging.

**Comment by seanh0895** [comment]
@lmangani Thank you for the quick response! So loosely speaking, if I get the gun multisocket service up and running over https I should be able swap the URL its hosted at to the multigun variable in the meething config.js? Or are there other critical issues that might prevent meething from working given the current state of the old infra? Also, do you know if the old multigun hosted at the meething domain differed from the repo you linked?

**Comment by lmangani** [comment]
@seanh0895 yes for pure p2p meething that's all that's needed
The old multigun was (and still is) running on glitch

**Comment by lmangani** [comment]
@seanh0895 https://meet.meething.space still works fine and uses the new serverless infrastructure
