### ISSUE TITLE
Off the grid mode

### ISSUE THREAD

**Issue by QVDev** [meething/webrtc-gun#28]
We would like to be able to disconnect from super peers so all people in the room are locked in to a private mode and nobody new can join. There is already some example code in presence.js and iris.to has also example code 

https://github.com/irislib/iris-messenger/blob/04a03d93dd4c1cc2c5be1f8e591269e1e2be908c/src/js/app.js#L111

also need a new button for this on top

**Comment by Dletta** [comment]
Webex calls this ‘locking the call’. Maybe calling it locking the room. Looks like firing a bye event closes the socket to that peer

**Comment by QVDev** [comment]
@Dletta feel free to take this over if you like it. I made a beginning in the presence.js called of the grid. You can rename it to whatever you want to logic became a bit cricket but it works. But getting on the grid is not working as I wrongly replace the peers.

**Comment by Dletta** [comment]
Is this something I can test via glitch test?

**Comment by QVDev** [comment]
Yeah https://meething-webrtc-qvdev.glitch.me/?room=qvdev
But you need to get into the console and call presence.offGrid()  and from there you can debug and improve on it. You can also remix that one and you will be able to edit the code

**Comment by Dletta** [comment]
I’ll try tonight.

**Comment by Dletta** [comment]
okay, created Fork, created Button, added Logic to call offGrid(), however:

onGrid function does not create a proper peer list in root._.opt.peers

Instead of 
```
{
"peer.com/gun":{object of stuff}
}
```
it comes out as 
```
 root._.opt.peers
22:05:52.679
Object {  }

22:06:35.878 root._.opt.peers
22:06:35.900
Object { 1: "https://gundb-multiserver.glitch.me/test_mp4xhwfko9", "https://gundb-multiserver.glitch.me/test_mp4xhwfko9": {…} }
```
which ends up in an error during 
offGrid()

@lmangani is the syntax right 
```
let peers = [];
  peers.push(peer);
  root.opt({peers:peers})
```

**Comment by QVDev** [comment]
AH yeah, that is correct as there are no peers, its gonna be the old peer that we probably have to save when we go off the grid / lock meeting. 

for every meeting there is a new gun instance node such as 
https://gundb-multiserver.glitch.me/qvdev

That is the magic of @lmangani of the multigun stuff. 

So the base that you wanna put back is 

```
var roomPeer = "https://gundb-multiserver.glitch.me/" + roomname;
var peers = [roomPeer]
root.opt({peers:peers})

```

**Comment by Dletta** [comment]
@QVDev using that syntax creates a weird index object, which triggers an error in offGrid

**Comment by QVDev** [comment]
So putting it back does no work? 

`root.opt({ peers: peers })` is the problem?

**Comment by Dletta** [comment]
Yes, it puts it twice basically, so when you iterate over keys in offGrid it fails to remove one because it’s undefined.

I’ll dig deeper to emulate more of how gun adds peers, so we don’t have to rely on the opt event to add the room as a peer

**Comment by Dletta** [comment]
How do you link a PR to an issue? PR #31 is the very first basic step for this.

**Comment by QVDev** [comment]
I linked the pr but seems there was some issue, you can push again to the same branch and reopen once you ready

**Comment by Dletta** [comment]
I'll pull over to my fork, resolve any conflicts and open a new PR.

**Comment by Dletta** [comment]
Adding note:” for now just lock/unlock will work, I guess unlock will try reattach to the multisocket peer with /roomName”

**Comment by lmangani** [comment]
@Dletta correct as the room name (in theory) is only known to existing participants - this way they can allow new ones to join etc. Thanks a bunch!
