### ISSUE TITLE
Video doesn't work

### ISSUE THREAD

**Issue by yisiliu** [meething/webrtc-gun#3]
My friends and I tried https://meething-webrtc-gun.glitch.me/ today but we found that the video chat cannot be enabled due to an exception 
`Uncaught TypeError: myStream.getVideoTracks is not a function at HTMLButtonElement.<anonymous> (rtc.js:308)`

You probably need to update the deployed version or did we miss anything?

We are using `Chrome Version 80.0.3987.149 (Official Build) (64-bit)`

**Comment by lmangani** [comment]
Hello @yisiliu 
Thanks for giving this a try! The glitch version is a "realtime" dev so it might contain dev bugs. The error you're pointing at suggests there are no streams or perhaps video permissions.
```
            myStream.getVideoTracks()[0].enabled = !(myStream.getVideoTracks()[0].enabled);
```

Chrome is what we're using so that's fine. Which OS are you using?
Could you attach the browser console logs before the issue strikes?

**Comment by yisiliu** [comment]
Thanks for the quick response! I am using OS X Catalina 10.15.3
The full console log is as follows:
```
gun.js:973 Hello wonderful person! :) Thanks for using GUN, please ask for help on http://chat.gun.eco if anything takes you longer than 5min to figure out!
three.r95.min.js:175 THREE.WebGLRenderer 95
DevTools failed to parse SourceMap: chrome-extension://iplppiggblloelhoglpmkmbinggcaaoc/app/content.js.map
rtc.js:53 Starting! you are 94e1834e-4080-4722-b6c6-079d88813165
rtc.js:42 debug emit key subscribe value {room: "Test_ekvm52qf0xa", socketId: "94e1834e-4080-4722-b6c6-079d88813165", name: "yisiliu"}
rtc.js:308 Uncaught TypeError: myStream.getVideoTracks is not a function
    at HTMLButtonElement.<anonymous> (rtc.js:308)
```
Before reporting this issue, I have manually enabled the video and audio permission in the site setting but it still didn't work.

**Comment by lmangani** [comment]
That's interesting the function should not be triggered unless you receive an invite. Did you open two windows/tabs with the room or were you alone?

**Comment by yisiliu** [comment]
I opened multiple tabs of two rooms - sorry about that mess. Let me clean it up and try again in incognito.

**Comment by yisiliu** [comment]
```
Hello wonderful person! :) Thanks for using GUN, please ask for help on http://chat.gun.eco if anything takes you longer than 5min to figure out!
three.r95.min.js:175 THREE.WebGLRenderer 95
rtc.js:53 Starting! you are ca3e90f9-45f2-4600-b95a-82bf120659e4
rtc.js:42 debug emit key subscribe value {room: "test-yisiliu_hcby1rfb1hn", socketId: "ca3e90f9-45f2-4600-b95a-82bf120659e4", name: "yisiliu"}
?room=test-yisiliu_hcby1rfb1hn:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://use.fontawesome.com/releases/v5.7.2/webfonts/fa-solid-900.woff2
rtc.js:308 Uncaught TypeError: myStream.getVideoTracks is not a function
    at HTMLButtonElement.<anonymous> (rtc.js:308)
```

**Comment by lmangani** [comment]
Can't really replicate it. Are you manually clicking the video icon? The local video only appears upon someone joining. The first session should have no output until someone else joins. No need to click anywhere (if that was the case)

Please try this:
- Create a new conference, brand new name and join it. Nothing shoud happen.
- Open the full link in a new tab. Enter a username. 
- Watch the console.log of the first session for errors if no video frames appear.


Not sure, but I'm afraid this might also have something to do with it:
`[Intervention] Slow network is detected`

I've never seen this before but it definitely WOULD impact usage. We should push an update using more peers later and it should mitigate the issue reaching the first Gun peer.

**Comment by yisiliu** [comment]
Weird - it works in this setting. Let me try it out with my friends then.

Regarding the gun peer - we can provide one at Linode Tokyo.

**Comment by lmangani** [comment]
@yisiliu that would be an amazing contribution! 

Note: 1-to-1 should work fine (ICE permitting) while 3-way and up signaling up still buggy on the joining and notify parts, so you might have to reload multiple times to see each other above 2 participants with this version.

**Comment by yisiliu** [comment]
Thanks! Let's close this issue until further similar issues pop up again. I will test it with my friends and let you know about our experience.

BTW We are also using GUNDB and you can check out our repo at https://github.com/dimensiondev/maskbook.

**Comment by lmangani** [comment]
That's awesome. The "chat" component of this demo is total garbage and would be nice to integrate with your project if possible. Feel free to open an issue if you'd like to explore that anytime!
