### ISSUE TITLE
Multiparty Video doesnt seem to be working

### ISSUE THREAD

**Issue by InformationArchitect** [meething/webrtc-gun#32]
Tried an informal qa test half an hour ago first with 5-11 users (not sure how many actually entered the room since i saw only up to 2 empty video frames at a time) and then with 3 users and had the same issue with empty frames. Will do better in future with bug reporting documentation but i attached the log from both the big chaotic call (test 1) and the second call/room with 3 people sharing video and audio. Will try to do this again with better logging and 2-3 users tomorrow morning (EST so 9 hrs from now)

First Test 5-11 Users
[test1_5-11Users.log](https://github.com/meething/webrtc-gun/files/4498283/test1_5-11Users.log)

Second Test With Different Room and 3 users
[test2_3Users.log](https://github.com/meething/webrtc-gun/files/4498284/test2_3Users.log)

A couple unedited screenshots with some shrank unfortunately by receiving over messenger (Unordered)
![image](https://user-images.githubusercontent.com/12848421/79678561-e2ff9900-81ca-11ea-8d6c-f2f3d709ce5d.png)

![image](https://user-images.githubusercontent.com/12848421/79678576-07f40c00-81cb-11ea-8310-3e04f25ceece.png)

My own
![image](https://user-images.githubusercontent.com/12848421/79678645-a1232280-81cb-11ea-9a98-327a2756fbad.png)

unique issue with no other users shown on ipad i guess?
![image](https://user-images.githubusercontent.com/12848421/79678610-50132e80-81cb-11ea-8d06-97a791ad4316.png)

**Comment by InformationArchitect** [comment]
Oof forgot to turn off ad and tracker blocking extensions so not sure if that played a role. Will try to retry and troubleshoot tomorrow.

**Comment by jabis** [comment]
I believe this has to do with #13 - the turn (Traversal Using Relay NAT) server used in the glitch-configs refuses to serve candidates, probably went over the bandwidth limit - we're at work with @lmangani to set up a coturn server at the moment.

**Comment by InformationArchitect** [comment]
Ok will it most likely be some third party TURN hosting platform like this
https://xirsys.com/ or just a custom vps with coturn or something like that?

**Comment by lmangani** [comment]
@InformationArchitect correct and replaced. I'm having issues with the glitch version myself, but self-hosted work fine. Please join the new discord for links!

**Comment by QVDev** [comment]
@InformationArchitect @lmangani Is this one still valid?

**Comment by InformationArchitect** [comment]
I dont think so? I will close it and maybe reopen one for the issues with the glitch instance specifically since thats what I QA tested but can you resend the latest links as they change on the weekly planning issue or send them in the testing channel on discord since that might be easiest? I think they got buried in discord as I cant find them.
