### ISSUE TITLE
Mic and video not working

### ISSUE THREAD

**Issue by benkenobi007** [meething/webrtc-gun#39]
**Branch**: Master
**OS:** Linux 64 bit (Manjaro)
**Browsers Tested:** Firefox and Firefox Dev
**Networks Tested:** Broadband, and mobile data

**Observed Behaviour:** 
Upon creating and entering a room, there's no popup asking for mic and camera. Only the chat window and user widget appear. This was observed when running it locally as well as on the web.

**Link:** http://meething-webrtc-gun.glitch.me/?room=room1_st51wyukt7p

Console error, warning logs, and screenshot are attached below.

****
[Console_log.txt](https://github.com/meething/webrtc-gun/files/4503239/Console_log.txt)
[Console_log_errors.txt](https://github.com/meething/webrtc-gun/files/4503244/Console_log_errors.txt)
[no_video_issue](https://user-images.githubusercontent.com/21176284/79748644-6801c400-832b-11ea-815d-55df9c8f4568.png)
****

**Note:** Other meeting clients work without any issue.

**Comment by QVDev** [comment]
http://meething-webrtc-gun.glitch.me/?room=room1_st51wyukt7p

Should be https like

https://meething-webrtc-gun.glitch.me/?room=room1_st51wyukt7p

Try that link to see if it works

**Comment by lmangani** [comment]
You MUST use HTTPS for anything webRTC related. We can help you in Discord but this is not an issue, rather a requirement. Thanks!

**Comment by lmangani** [comment]
Feel free to attach additional logs if neeeded.
