### ISSUE TITLE
Local Audio/Video Mute functions not working

### ISSUE THREAD

**Issue by lmangani** [meething/webrtc-gun#4]

**Comment by amirsanni** [comment]
Is there any error in the console when the buttons are clicked?

**Comment by lmangani** [comment]
Hey @amirsanni 
The issue seems to be with the actual functions called by the buttons, which are indeed fine. 
Title updated :)

**Comment by amirsanni** [comment]
I get that. I mean is there any error when the functions are invoked?

**Comment by lmangani** [comment]
No, I'm still investigating it as you can see on the demo no errors are triggered, although the code seems correct. You can check it by opening two sessions at https://meething-webrtc-gun.glitch.me

**Comment by amirsanni** [comment]
Alright. Will check it out.

**Comment by lmangani** [comment]
I think we should target and set the local devices directly here to apply for all streams?
```
var localMedia = await navigator.mediaDevices.getUserMedia({
audio: true,
video: false
})
```

**Comment by amirsanni** [comment]
I think the best thing will be to toggle the `enabled` property of the `audioTrack` when the button is clicked and then use `replaceTrack` to broadcast to all peers.

Will try to do this later today.

**Comment by QVDev** [comment]
Anyone that can help here or can have a look to fix this? Seems to getting a must to able to mute yourself etc...

**Comment by Dletta** [comment]
Video on/off worked on one side, mute I haven’t been able to test yet.

**Comment by jabis** [comment]
@QVDev Like @amirsanni mentioned, the local audio track, when muted, is not sent to peers,
What I added with the merged screenshare-branch was also `helpers.replaceAudioTrackForPeers` so it should be easy to set the `audiotrack = stream.getAudioTracks()[0]; audiotrack.enabled = !!audiotrack.enabled;`  and then call `h.replaceAudioTrackForPeers(pcmap,audiotrack);` - it's a bit too late here (3.37am) so I won't be touching this one today anymore, but that's how you can do it 🦝
